Repository DioxusLabs/manganis, pull requests merged in 2024-07, with the labels that each got.

#30 Linker-Based Asset Propogation
  .gitignore
  Cargo.lock
  cli-support/Cargo.toml
  cli-support/README.md
  cli-support/examples/cli.rs
  cli-support/src/cache.rs
  cli-support/src/lib.rs
  cli-support/src/linker_intercept.rs
  cli-support/src/manifest.rs
  cli-support/tests/collects_assets.rs
  common/src/asset.rs
  common/src/cache.rs
  common/src/config.rs
  common/src/lib.rs
  common/src/linker.rs
  common/src/manifest.rs
  common/src/package.rs
  dist/tailwind.css
  macro/Cargo.toml
  macro/build.rs
  macro/src/file.rs
  macro/src/font.rs
  macro/src/image.rs
  macro/src/lib.rs
  test-package/Cargo.toml
  test-package/src/main.rs
  test-package/test-package-dependency/src/file.rs
  test-package/test-package-nested-dependency/src/file.rs
Labels: bug

#33 Fix link section name when cross compiling
  cli-support/src/manifest.rs
  cli-support/tests/collects_assets.rs
  common/src/config.rs
  common/src/linker.rs
  macro/src/lib.rs
Labels: bug

#37 Filesystem Fallback For Desktop
  cli-support/examples/cli.rs
  common/src/asset.rs
  macro/src/file.rs
  macro/src/font.rs
  macro/src/image.rs
  macro/src/lib.rs
  test-package/src/main.rs
Labels: enhancement

#38 Only preload css in the head; don't load css automatically
  cli-support/tests/collects_assets.rs
  common/src/file.rs
  common/src/manifest.rs
  macro/src/css.rs
  macro/src/lib.rs
  src/lib.rs
Labels: breaking

#48 include the manganis-common version in the file name hash
  Cargo.lock
  common/Cargo.toml
  common/build.rs
  common/src/asset.rs
  common/src/built.rs
  common/src/lib.rs
Labels: bug

#51 Make absolute links relative to the crate root
  assets/asset.txt
  common/src/asset.rs
  src/lib.rs
  test-package/src/main.rs
Labels: breaking

#49 Don't allow libraries to preload at compile time
  macro/src/css.rs
  macro/src/image.rs
  macro/src/js.rs
  macro/src/json.rs
  macro/src/lib.rs
Labels: breaking
